// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: account.sql

package database

import (
	"context"
	"time"
)

const registerAccount = `-- name: RegisterAccount :exec
INSERT INTO accounts (id, email, created_at)
VALUES ($1, $2, $3)
`

type RegisterAccountParams struct {
	ID        string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) RegisterAccount(ctx context.Context, arg RegisterAccountParams) error {
	_, err := q.db.ExecContext(ctx, registerAccount, arg.ID, arg.Email, arg.CreatedAt)
	return err
}
