// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Agent struct {
	AccountID       string
	Token           string
	Symbol          string
	Headquarters    string
	Credits         int64
	StartingFaction string
	ShipCount       int32
}

type Cargo struct {
	ID          int32
	Capacity    int32
	Units       int32
	InventoryID int32
}

type Consumed struct {
	ID       int32
	Amount   int32
	Timestmp time.Time
}

type Contract struct {
	ID               string
	FactionSymbol    string
	Type             string
	TermsID          int32
	Accepted         bool
	Fulfilled        bool
	DeadlineToAccept time.Time
}

type Cooldown struct {
	ID               int32
	ShipSymbol       string
	TotalSeconds     int32
	RemainingSeconds int32
	Expiration       time.Time
}

type Crew struct {
	ID       int32
	Current  int32
	Required int32
	Capacity int32
	Rotation string
	Morale   int32
	Wages    int32
}

type Deliver struct {
	ID                int32
	TradeSymbol       string
	DestinationSymbol string
	UnitsRequired     int32
	UnitsFulfilled    int32
}

type Destination struct {
	ID           int32
	Symbol       string
	Type         string
	SystemSymbol string
	X            int32
	Y            int32
}

type Engine struct {
	ID            int32
	Symbol        string
	Name          string
	Condition     float64
	Integrity     float64
	Description   string
	Speed         int32
	RequirementID int32
	Quality       int32
}

type Faction struct {
	ID           int32
	Symbol       string
	Name         string
	Description  string
	Headquarters string
	TraitID      int32
	IsRecruiting bool
}

type Frame struct {
	ID             int32
	Symbol         string
	Name           string
	Condition      float64
	Integrity      float64
	Description    string
	ModuleSlots    int32
	MountingPoints int32
	FuelCapacity   int32
	RequirementID  int32
	Quality        int32
}

type Fuel struct {
	ID         int32
	Current    int32
	Capacity   int32
	ConsumedID int32
}

type Inventory struct {
	ID          int32
	Symbol      string
	Name        string
	Description string
	Units       int32
}

type Module struct {
	ID            int32
	Symbol        string
	Name          string
	Description   string
	Capacity      int32
	Range         int32
	RequirementID int32
}

type Mount struct {
	ID            int32
	Symbol        string
	Name          string
	Description   string
	Strength      int32
	Deposits      []string
	RequirementID int32
}

type Nav struct {
	ID             int32
	SystemSymbol   string
	WaypointSymbol string
	RouteID        int32
	Status         string
	FlightMode     string
}

type Origin struct {
	ID           int32
	Symbol       string
	Type         string
	SystemSymbol string
	X            int32
	Y            int32
}

type Payment struct {
	ID          int32
	OnAccepted  int32
	OnFulfilled int32
}

type Reactor struct {
	ID            int32
	Symbol        string
	Name          string
	Condition     float64
	Integrity     float64
	Description   string
	PowerOutput   int32
	RequirementID int32
	Quality       int32
}

type Registration struct {
	ID            int32
	Name          string
	FactionSymbol string
	Role          string
}

type Requirement struct {
	ID    int32
	Power int32
	Crew  int32
	Slots int32
}

type Route struct {
	ID            int32
	DestinationID int32
	OriginID      int32
	DepartureTime time.Time
	Arrival       time.Time
}

type Ship struct {
	ID             int32
	Symbol         string
	RegistrationID int32
	NavID          int32
	CrewID         int32
	FrameID        int32
	ReactorID      int32
	EnginesID      int32
	ModuleID       int32
	MountID        int32
	CargoID        int32
	FuelID         int32
	CooldownID     int32
}

type Term struct {
	ID        int32
	Deadline  time.Time
	PaymentID int32
	DeliverID int32
}

type Token struct {
	ID string
}

type Trait struct {
	ID          int32
	Symbol      string
	Name        string
	Description string
}
