// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: register_agent.sql

package database

import (
	"context"
)

const registerAgent = `-- name: registerAgent :one
INSERT INTO agents (account_id, token, symbol, headquarters, credits, starting_faction, ship_count)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING account_id, token, symbol, headquarters, credits, starting_faction, ship_count
`

type registerAgentParams struct {
	AccountID       string
	Token           string
	Symbol          string
	Headquarters    string
	Credits         int64
	StartingFaction string
	ShipCount       int32
}

func (q *Queries) registerAgent(ctx context.Context, arg registerAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, registerAgent,
		arg.AccountID,
		arg.Token,
		arg.Symbol,
		arg.Headquarters,
		arg.Credits,
		arg.StartingFaction,
		arg.ShipCount,
	)
	var i Agent
	err := row.Scan(
		&i.AccountID,
		&i.Token,
		&i.Symbol,
		&i.Headquarters,
		&i.Credits,
		&i.StartingFaction,
		&i.ShipCount,
	)
	return i, err
}
